### ISSUE TITLE
Not all Japanese characters monowidth (either 1000 or 500)

### ISSUE THREAD

**Issue by aaronbell** [positype/Murecho-Project#3]
Please review / correct the widths of these glyphs:

/rusmall-kata
/resmall-kata
/rosmall-kata
/wasmall-kata
/ti-kata.half
/te-kata.half
/to-kata.half
/na-kata.half
/no-kata.half
/hu-kata.half
/hosmall-kata
/yasmall-kata.half
/yusmall-kata.half
/ri-kata.half
/ru-kata.half
/re-kata.half
/wasmall-kata.vert
/repeatLowerhalf-kana
/repeatUpperhalf-kana
/repeatVoicedUpperhalf-kana

**Comment by positype** [comment]
Aaron,

Thanks for catching these… I caught a few others in symbols and other extraneous glyphs and obviously fixed those but I had a question about repeat*-kana glyphs… were you suggesting they needed to be something other than 1000? That’s what they were and I checked my previous typefaces and Ken’s book to make sure… if you have some additional insight I am missing, please yell at me.

Thanks.

*N

Neil Summerour

POSITYPE  Type Designer
positype.com
***@***.***    FACEBOOK  positype
---
TYPECON & SOTA  Conference Chair
typecon.com    typesociety.org

**Comment by aaronbell** [comment]
Huh! I had a script that created that list, but rewriting it now, I'm not seeing those repeat items come up. Must have done something wrong before. Sorry!

**Comment by positype** [comment]
“I had a script that created that list”

🤯

Neil Summerour

POSITYPE  Type Designer
positype.com
***@***.***    FACEBOOK  positype
---
TYPECON & SOTA  Conference Chair
typecon.com    typesociety.org

**Comment by aaronbell** [comment]
Pretty simple! Select some glyphs and run in the macro panel
```
for glyph in Glyphs.font.selection:
	for layer in glyph.layers:
		if layer.width == 1000:
			pass
		elif layer.width == 500 and "half" in glyph.name:
			pass
		else:
			print glyph.name, layer.name, layer.width
```

**Comment by aaronbell** [comment]
I found one still remaining:
Light weight /hosmall-kata (ㇹ) is 1001

**Comment by positype** [comment]
Fixed. Thanks.

Neil Summerour

POSITYPE  Type Designer
positype.com
***@***.***    FACEBOOK  positype
---
TYPECON & SOTA  Conference Chair
typecon.com    typesociety.org

**Comment by aaronbell** [comment]
Thanks!
