### ISSUE TITLE
Spacing oddities

### ISSUE THREAD

**Issue by aaronbell** [positype/Murecho-Project#4]
- The `HJ` pair in particular seems really strange (-94), causing an unexpected overlap.
- `Dje-cy` has a really large right side bearing

It would be worth reviewing / correcting spacing & kerning of Latin / Cyrillic / Greek letters to ensure that spacing is proper.

**Comment by aaronbell** [comment]
`Dje-cy` looks better.

I took a glance through the kerning otherwise, and found another weird situation.

The center pair is extremely tight:
<img width="436" alt="Screen Shot 2021-09-01 at 2 45 57 PM" src="https://user-images.githubusercontent.com/8460297/131749555-11ca14a9-54b7-4673-8cb2-80a767ee119c.png">
And in the Black, there is no kern:
<img width="518" alt="Screen Shot 2021-09-01 at 2 46 15 PM" src="https://user-images.githubusercontent.com/8460297/131749578-0a98afa2-0d8a-4527-8f72-978e6f49038d.png">

As I mentioned in the original bug, it would be worth reviewing the kern data / spacing to ensure that things are rendering evenly.

**Comment by positype** [comment]
This confuses me… in my master, local, these pairs are different with different values, and carried through both masters. I’ve made sure this is ‘back in’ and included it with the most recent updated push… one thing though… this was not the only occurrence where I found one set of kerning/spacing data, versus what was in the master… I’ve double checked everything again, saved a new local to compare it against if anything else happens.

Thanks for catching this.

*N

Neil Summerour

POSITYPE  Type Designer
positype.com
***@***.***    FACEBOOK  positype
---
TYPECON & SOTA  Conference Chair
typecon.com    typesociety.org

**Comment by aaronbell** [comment]
Thanks!
