### ISSUE TITLE
Inconsistent stroke thicknesses

### ISSUE THREAD

**Issue by aaronbell** [positype/Murecho-Project#5]
<img width="1043" alt="Screen Shot 2021-07-26 at 12 07 30 PM" src="https://user-images.githubusercontent.com/8460297/127044749-668bae06-5481-4247-8f95-053db953258c.png">

It would be worth looking at the relative thicknesses. Observe the modulation in stroke in the round of the `Φ` versus the `O` (particularly at diagonals) and the thinness of the diagonals in the `Y` comparatively.

**Comment by aaronbell** [comment]
The /O and other rounds are looking better, but I think that the diagonals are still not quite there yet. In the case of the `Y`, the diagonal width is the same as the vertical width (both are 20 units). As a result, the diagonals feel quite light compared to the vertical stem. Also compare with the `κ` where the stem widths are `24` and `26`. 

I think it would be worth taking a look at the diagonals across the Latins and making sure the weights align well.

**Comment by positype** [comment]
Aaron,

I see what you mean now that I look at it and cannot figure out how/why some of these were overlooked. I’ve reviewed through Latin, Cyrillic, and Greek and feel better with these adjustments.

Neil Summerour

POSITYPE  Type Designer
positype.com
***@***.***    FACEBOOK  positype
---
TYPECON & SOTA  Conference Chair
typecon.com    typesociety.org

**Comment by aaronbell** [comment]
Looks better. Thanks!
