### ISSUE TITLE
Position of diacritic over stems?

### ISSUE THREAD

**Issue by aaronbell** [positype/Murecho-Project#6]
I note that the `h` and `k` have diacritics positioned differently. Should these be positioned consistently? 

<img width="439" alt="Screen Shot 2021-07-26 at 12 17 27 PM" src="https://user-images.githubusercontent.com/8460297/127045951-9f16f568-00f0-4425-8fad-2e0926cb5032.png">

**Comment by positype** [comment]
Bah. I’ll pass on to Potch ASAP. He completed and cleared those.

Thanks!

Neil Summerour

POSITYPE  Type Designer
positype.com
***@***.***    FACEBOOK  positype
---
TYPECON & SOTA  Conference Chair
typecon.com    typesociety.org

**Comment by aaronbell** [comment]
👍
